name: Testing the Python code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install pycodestyle
          python -m pip install pytest
          python -m pip install --upgrade pip

      - name: Lint with pycodestyle
        run: |
          pycodestyle 1_lab/rating/src 1_lab/rating/test

      - name: Test with pytest
        run: |
          python -m src.main -p 1_lab/rating/data/data.txt
          python -m pytest 1_lab/rating/test

