name: Testing the Python code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f lab1/rating/requirements.txt ]; then pip install -r lab1/rating/requirements.txt; fi

      - name: Lint with pycodestyle
        run: |
          python -m pycodestyle lab1/rating/src lab1/rating/test

      - name: Test with pytest
        run: |
          python -m pytest lab1/rating/test

      - name: Test by running the program by data.txt
        run: |
          python -m lab1.rating.src.main -p lab1\rating\data\data.txt
      
      - name: Test by running the program by data_json.txt
        run: |
          python -m lab1.rating.src.main -p lab1\rating\data\data_json.json
